In [1]:
import tsraster
from tsraster import random

In [2]:
test_output = random.Poisson_Subsample(raster_mask = r"../Data\Examples\buffer\StatePoly_buf.tif",outFile = r"../Data\Examples\Poisson\PoissonTest_4.tif",  k=50, r=5)
print(test_output[0])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [3]:
import rasterio
import numpy as np
with rasterio.open(r"../Data\Examples\buffer\StatePoly_buf.tif") as exampleRast:
        array = exampleRast.read()
        profile = exampleRast.profile
        profile.update(dtype=rasterio.float32, count=1, compress='lzw',nodata=0)

f2Array = np.float32(test_output[0])      
        
with rasterio.open("../Data/Examples/Poisson/PoissonTest5.tif", 'w', **profile) as prob_iter:
    prob_iter.write(f2Array, 1)

In [4]:

array

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)

(1209, 941)

(1209, 941)